import LanguageChoose from "./LanguageChoose.tsx";
import { useState } from "react";
import LevelChoose from "./LevelChoose.tsx";
import TopicsChoose from "./TopicsChoose.tsx";
import GoalsChoose from "./GoalsChoose.tsx";
import { findUserById, updateUser } from "../services/users.ts";
import type { User } from "../models/user.ts";
import {useNavigate} from "react-router";

type MainPageMainProps = {
    getIsLoading: (isLoading: boolean) => void;
}

function MainPageMain({getIsLoading}: MainPageMainProps) {
    const navigate = useNavigate();

    const [selectedLanguage, setSelectedLanguage] = useState<string | null>(null);
    const [selectedLevel, setSelectedLevel] = useState<string | null>(null);
    const [selectedTopic, setSelectedTopic] = useState<string | null>(null);
    const [activeStep, setActiveStep] = useState(0);

    const getSelectedLanguage = (language: string) => {
        setSelectedLanguage(language);
        setActiveStep(1);
    };

    const getSelectedLevel = (level?: string, back?: boolean) => {
        if (level !== undefined) {
            setSelectedLevel(level);
            setActiveStep(activeStep + 1);
        }
        if (back) {
            setActiveStep(activeStep - 1);
        }
    };

    const getSelectedTopic = (topic?: string, back?: boolean)=> {
        if (topic !== undefined) {
            setSelectedTopic(topic);
            setActiveStep(activeStep + 1);
        }
        if (back) {
            setActiveStep(activeStep - 1);
        }
    }

    const getSelectedGoal = async (goal?: string, back?: boolean)=> {
        getIsLoading(true);
        if (back) {
            setActiveStep(activeStep - 1);
        }

        const userId = localStorage.getItem("currentUserId");
        if (userId) {
            const existingUser: User = await findUserById(userId);
            if (existingUser) {
                const newUser = {
                    ...existingUser,
                    id: userId,
                    language: selectedLanguage!,
                    level: selectedLevel!,
                    interests: selectedTopic!,
                    goals: goal!,

                };
                await updateUser(newUser);
                setTimeout(() => {
                    navigate("/workpage");
                    getIsLoading(false);
                }, 1500);

            }
        }
    }

    return (
        <>
            <div className="flex-1">
                <section
                    className="bg-gradient-to-r from-[#0F4C5C] to-[#1E6F8E]
                    text-white py-4 md:py-10 px-5 text-center"
                >
                    <div className="container mx-auto">
                        <h2 className="text-4xl font-bold py-2 md:py-2">Learn a language with AI</h2>
                        <p className="text-lg py-2 md:py-2">
                            Practice through personalized exercises generated by artificial
                            intelligence.
                        </p>
                    </div>
                </section>
                <section
                    className="md:py-10 py-5 px-5 text-center font-bold"
                >
                    <div className="flex items-center justify-center">
                        <LanguageChoose getSelectedLanguage={getSelectedLanguage} show={activeStep === 0} />
                        <LevelChoose getSelectedLevel={getSelectedLevel} show={activeStep === 1} />
                        <TopicsChoose getSelectedTopic={getSelectedTopic} show={activeStep === 2} />
                        <GoalsChoose getSelectedGoal={getSelectedGoal} show={activeStep === 3} />
                    </div>
                </section>
            </div>
        </>
    )
}

export default MainPageMain
