/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkPageRouteImport } from './routes/workPage'
import { Route as SignUpPageRouteImport } from './routes/signUpPage'
import { Route as MainPageRouteImport } from './routes/mainPage'
import { Route as LoginPageRouteImport } from './routes/loginPage'
import { Route as IndexRouteImport } from './routes/index'

const WorkPageRoute = WorkPageRouteImport.update({
  id: '/workPage',
  path: '/workPage',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpPageRoute = SignUpPageRouteImport.update({
  id: '/signUpPage',
  path: '/signUpPage',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPageRoute = MainPageRouteImport.update({
  id: '/mainPage',
  path: '/mainPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/loginPage',
  path: '/loginPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loginPage': typeof LoginPageRoute
  '/mainPage': typeof MainPageRoute
  '/signUpPage': typeof SignUpPageRoute
  '/workPage': typeof WorkPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loginPage': typeof LoginPageRoute
  '/mainPage': typeof MainPageRoute
  '/signUpPage': typeof SignUpPageRoute
  '/workPage': typeof WorkPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loginPage': typeof LoginPageRoute
  '/mainPage': typeof MainPageRoute
  '/signUpPage': typeof SignUpPageRoute
  '/workPage': typeof WorkPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loginPage' | '/mainPage' | '/signUpPage' | '/workPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loginPage' | '/mainPage' | '/signUpPage' | '/workPage'
  id:
    | '__root__'
    | '/'
    | '/loginPage'
    | '/mainPage'
    | '/signUpPage'
    | '/workPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginPageRoute: typeof LoginPageRoute
  MainPageRoute: typeof MainPageRoute
  SignUpPageRoute: typeof SignUpPageRoute
  WorkPageRoute: typeof WorkPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workPage': {
      id: '/workPage'
      path: '/workPage'
      fullPath: '/workPage'
      preLoaderRoute: typeof WorkPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signUpPage': {
      id: '/signUpPage'
      path: '/signUpPage'
      fullPath: '/signUpPage'
      preLoaderRoute: typeof SignUpPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mainPage': {
      id: '/mainPage'
      path: '/mainPage'
      fullPath: '/mainPage'
      preLoaderRoute: typeof MainPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loginPage': {
      id: '/loginPage'
      path: '/loginPage'
      fullPath: '/loginPage'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginPageRoute: LoginPageRoute,
  MainPageRoute: MainPageRoute,
  SignUpPageRoute: SignUpPageRoute,
  WorkPageRoute: WorkPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
